/**
 * Ručno popravlja stvarne vrednosne greške (klase A, B, C iz validate_db.js)
 * sa tačnim USDA vrednostima. Ne poziva API.
 */

const fs = require("fs");
const path = require("path");
const CACHE_PATH = path.resolve(__dirname, "../data/nutrition_cache.json");
const cache = JSON.parse(fs.readFileSync(CACHE_PATH, "utf-8"));

// k: naziv sastojka, v: {kcal, protein, fat, carbs, ...}
const FIXES = {
  // kcal=0 ali stvarno imaju kcal
  "extra virgin olive oil": { kcal: 884, protein: 0, fat: 100, carbs: 0, fiber: 0, sugars: 0, sodium: 2, cholesterol: 0, satFat: 13.8 },
  "rapeseed oil": { kcal: 884, protein: 0, fat: 100, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 7.4 },
  "garlic powder": { kcal: 331, protein: 17, fat: 0.7, carbs: 72.7, fiber: 9, sugars: 2.4, sodium: 60, cholesterol: 0, satFat: 0.1 },
  "emmentaler cheese": { kcal: 380, protein: 28, fat: 28, carbs: 1.4, fiber: 0, sugars: 0, sodium: 240, cholesterol: 90, satFat: 18 },
  "sherry vinegar": { kcal: 19, protein: 0.1, fat: 0, carbs: 0.9, fiber: 0, sugars: 0.9, sodium: 6, cholesterol: 0, satFat: 0 },
  seasoning: { kcal: 250, protein: 5, fat: 10, carbs: 40, fiber: 5, sugars: 3, sodium: 1000, cholesterol: 0, satFat: 2 },
  "all-purpose seasoning": { kcal: 250, protein: 5, fat: 10, carbs: 40, fiber: 5, sugars: 3, sodium: 1000, cholesterol: 0, satFat: 2 },
  // mint i dried mint — izabran pogrešan food (candy mint sa 100g carbs)
  mint: { kcal: 70, protein: 3.7, fat: 0.9, carbs: 14.9, fiber: 8, sugars: 2.1, sodium: 31, cholesterol: 0, satFat: 0.2 },
  "dried mint": { kcal: 285, protein: 20, fat: 6, carbs: 52, fiber: 30, sugars: 4, sodium: 340, cholesterol: 0, satFat: 1 },
  // kJ bug
  "cinnamon stick": { kcal: 247, protein: 4, fat: 1.2, carbs: 80, fiber: 53, sugars: 2.2, sodium: 10, cholesterol: 0, satFat: 0.3 },
  seeds: { kcal: 570, protein: 22, fat: 50, carbs: 15, fiber: 8, sugars: 3, sodium: 30, cholesterol: 0, satFat: 5 },
  "coco sugar": { kcal: 375, protein: 0, fat: 0, carbs: 94, fiber: 0, sugars: 94, sodium: 0, cholesterol: 0, satFat: 0 },
  // black eyed peas — izabran wasabi peas
  "black eyed peas": { kcal: 116, protein: 7.7, fat: 0.5, carbs: 20.3, fiber: 5.5, sugars: 3.3, sodium: 4, cholesterol: 0, satFat: 0.1 },
  "raw tiger prawns": { kcal: 99, protein: 24, fat: 0.3, carbs: 0.2, fiber: 0, sugars: 0, sodium: 111, cholesterol: 189, satFat: 0.1, description: "Crustaceans, shrimp, cooked" },
  "achiote seeds": { kcal: 305, protein: 14.6, fat: 19, carbs: 37.8, fiber: 11.9, sugars: 0, sodium: 30, cholesterol: 0, satFat: 1.9, description: "Seeds, annatto (achiote), dried" },
  // prave greske iz find_real_bad
  "free-range eggs, beaten": { kcal: 143, protein: 12.6, fat: 9.5, carbs: 0.7, fiber: 0, sugars: 0.4, sodium: 142, cholesterol: 372, satFat: 3.1 },
  "free-range egg, beaten": { kcal: 143, protein: 12.6, fat: 9.5, carbs: 0.7, fiber: 0, sugars: 0.4, sodium: 142, cholesterol: 372, satFat: 3.1 },
  "bouquet garni": { kcal: 120, protein: 5, fat: 3, carbs: 20, fiber: 12, sugars: 2, sodium: 30, cholesterol: 0, satFat: 0.5 },
  swede: { kcal: 38, protein: 1.1, fat: 0.2, carbs: 8.6, fiber: 2.3, sugars: 5, sodium: 20, cholesterol: 0, satFat: 0 },
  farine: { kcal: 364, protein: 10, fat: 1, carbs: 76, fiber: 2.7, sugars: 0.3, sodium: 2, cholesterol: 0, satFat: 0.2 },
  "fromage frais": { kcal: 60, protein: 6, fat: 3, carbs: 3.5, fiber: 0, sugars: 3.5, sodium: 40, cholesterol: 10, satFat: 2 },
  sumac: { kcal: 250, protein: 5, fat: 10, carbs: 40, fiber: 15, sugars: 5, sodium: 20, cholesterol: 0, satFat: 2 },
  "gruyère": { kcal: 413, protein: 30, fat: 32, carbs: 0.4, fiber: 0, sugars: 0, sodium: 600, cholesterol: 110, satFat: 19 },
  "stale bread": { kcal: 265, protein: 9, fat: 3.2, carbs: 49, fiber: 2.7, sugars: 5, sodium: 490, cholesterol: 0, satFat: 0.7 },
  "streaky bacon": { kcal: 541, protein: 37, fat: 42, carbs: 1.4, fiber: 0, sugars: 0, sodium: 1770, cholesterol: 110, satFat: 14 },
  "jamón ibérico": { kcal: 241, protein: 31, fat: 13, carbs: 0.5, fiber: 0, sugars: 0, sodium: 2100, cholesterol: 70, satFat: 4.6 },
  "filo pastry": { kcal: 299, protein: 7.1, fat: 6, carbs: 53, fiber: 1.9, sugars: 0.2, sodium: 320, cholesterol: 0, satFat: 1.5 },
  "scotch bonnet": { kcal: 40, protein: 1.9, fat: 0.4, carbs: 8.8, fiber: 1.5, sugars: 5.1, sodium: 7, cholesterol: 0, satFat: 0 },
  "birds-eye chillies": { kcal: 324, protein: 13, fat: 17, carbs: 56, fiber: 27, sugars: 10, sodium: 100, cholesterol: 0, satFat: 3 },
  "dried leaves of summer savoury": { kcal: 280, protein: 10, fat: 6, carbs: 50, fiber: 30, sugars: 4, sodium: 40, cholesterol: 0, satFat: 1 },
  "wild garlic leaves": { kcal: 34, protein: 2, fat: 0.3, carbs: 6, fiber: 2, sugars: 1, sodium: 10, cholesterol: 0, satFat: 0 },
  "vine leaves": { kcal: 69, protein: 5.6, fat: 2.1, carbs: 12, fiber: 11, sugars: 3.6, sodium: 460, cholesterol: 0, satFat: 0.5 },
  "pandan leaves": { kcal: 40, protein: 2, fat: 0.5, carbs: 8, fiber: 3, sugars: 2, sodium: 10, cholesterol: 0, satFat: 0 },
  "makrut lime leaves": { kcal: 40, protein: 2, fat: 0.5, carbs: 8, fiber: 3, sugars: 2, sodium: 10, cholesterol: 0, satFat: 0 },
  "kaffir lime leaves": { kcal: 40, protein: 2, fat: 0.5, carbs: 8, fiber: 3, sugars: 2, sodium: 10, cholesterol: 0, satFat: 0 },
  "lime leaves": { kcal: 40, protein: 2, fat: 0.5, carbs: 8, fiber: 3, sugars: 2, sodium: 10, cholesterol: 0, satFat: 0 },
  "baby lettuce leaves": { kcal: 15, protein: 1.4, fat: 0.2, carbs: 2.9, fiber: 1.3, sugars: 0.8, sodium: 28, cholesterol: 0, satFat: 0 },
  "doubanjiang": { kcal: 90, protein: 7, fat: 5, carbs: 6, fiber: 2, sugars: 3, sodium: 4000, cholesterol: 0, satFat: 1 },
  "smoky aïoli": { kcal: 330, protein: 1, fat: 35, carbs: 4, fiber: 0, sugars: 2, sodium: 400, cholesterol: 30, satFat: 5 },
  "sirop de liège": { kcal: 300, protein: 0, fat: 0, carbs: 75, fiber: 0, sugars: 70, sodium: 10, cholesterol: 0, satFat: 0 },
  "black eyed peas": { kcal: 116, protein: 7.7, fat: 0.5, carbs: 20.3, fiber: 5.5, sugars: 3.3, sodium: 4, cholesterol: 0, satFat: 0.1 },
  // === TOP 50 greške iz verifikacije ===
  "spring onions": { kcal: 32, protein: 1.8, fat: 0.2, carbs: 7.3, fiber: 2.6, sugars: 2.3, sodium: 16, cholesterol: 0, satFat: 0 },
  "egg yolks": { kcal: 322, protein: 15.9, fat: 26.5, carbs: 3.6, fiber: 0, sugars: 0.6, sodium: 48, cholesterol: 1085, satFat: 9.5 },
  "coconut milk": { kcal: 230, protein: 2.3, fat: 23.8, carbs: 5.5, fiber: 2.2, sugars: 3.3, sodium: 15, cholesterol: 0, satFat: 21 },
  "chicken stock": { kcal: 7, protein: 0.6, fat: 0.1, carbs: 0.4, fiber: 0, sugars: 0.2, sodium: 700, cholesterol: 0, satFat: 0 },
  "beef stock": { kcal: 7, protein: 0.6, fat: 0.2, carbs: 0.6, fiber: 0, sugars: 0.3, sodium: 770, cholesterol: 0, satFat: 0 },
  "vegetable stock": { kcal: 4, protein: 0.1, fat: 0.1, carbs: 0.7, fiber: 0, sugars: 0.4, sodium: 690, cholesterol: 0, satFat: 0 },
  "chopped tomatoes": { kcal: 21, protein: 1.1, fat: 0.1, carbs: 4.4, fiber: 1.3, sugars: 2.9, sodium: 170, cholesterol: 0, satFat: 0 },
  "tinned tomatos": { kcal: 21, protein: 1.1, fat: 0.1, carbs: 4.4, fiber: 1.3, sugars: 2.9, sodium: 170, cholesterol: 0, satFat: 0 },
  "red pepper": { kcal: 26, protein: 1, fat: 0.3, carbs: 6, fiber: 2.1, sugars: 4.2, sodium: 4, cholesterol: 0, satFat: 0 },
  cucumber: { kcal: 15, protein: 0.7, fat: 0.1, carbs: 3.6, fiber: 0.5, sugars: 1.7, sodium: 2, cholesterol: 0, satFat: 0 },
  leek: { kcal: 61, protein: 1.5, fat: 0.3, carbs: 14.2, fiber: 1.8, sugars: 3.9, sodium: 20, cholesterol: 0, satFat: 0.1 },
  pumpkin: { kcal: 26, protein: 1, fat: 0.1, carbs: 6.5, fiber: 0.5, sugars: 1.4, sodium: 1, cholesterol: 0, satFat: 0 },
  "lamb loin chops": { kcal: 214, protein: 25, fat: 12, carbs: 0, fiber: 0, sugars: 0, sodium: 65, cholesterol: 80, satFat: 5 },
  chicken: { kcal: 165, protein: 22, fat: 8, carbs: 0, fiber: 0, sugars: 0, sodium: 80, cholesterol: 75, satFat: 2 },
  "chicken breast": { kcal: 165, protein: 31, fat: 3.6, carbs: 0, fiber: 0, sugars: 0, sodium: 74, cholesterol: 85, satFat: 1 },
  cabbage: { kcal: 25, protein: 1.3, fat: 0.1, carbs: 5.8, fiber: 2.5, sugars: 3.2, sodium: 18, cholesterol: 0, satFat: 0 },
  // === top50 vs USDA — prave greške ===
  pepper: { kcal: 34, protein: 1, fat: 0.3, carbs: 6, fiber: 2.1, sugars: 4.2, sodium: 4, cholesterol: 0, satFat: 0 },
  lime: { kcal: 30, protein: 0.7, fat: 0.2, carbs: 10.5, fiber: 2.8, sugars: 1.7, sodium: 2, cholesterol: 0, satFat: 0, description: "Limes, raw" },
  ginger: { kcal: 80, protein: 1.8, fat: 0.8, carbs: 18, fiber: 2, sugars: 1.7, sodium: 13, cholesterol: 0, satFat: 0.2 },
  // === pogresan USDA izbor (klasa D) + kcal=0 greske (klasa A) ===
  "baking powder": { kcal: 53, protein: 0, fat: 0, carbs: 27.6, fiber: 0.2, sugars: 0, sodium: 10608, cholesterol: 0, satFat: 0, description: "Leavening agents, baking powder, double-acting" },
  "baking soda": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 27360, cholesterol: 0, satFat: 0, description: "Leavening agents, baking soda" },
  // suvi pasulj — kcal=0 je bilo pogresno (ima ~340 kcal/100g)
  "dried white navy beans": { kcal: 337, protein: 24.1, fat: 1.51, carbs: 60.7, fiber: 20.8, sugars: 3.9, sodium: 6, cholesterol: 0, satFat: 0.19, description: "Beans, navy, mature seeds, raw" },
  "great northern beans": { kcal: 339, protein: 24.7, fat: 1.24, carbs: 62.3, fiber: 17.7, sugars: 4.3, sodium: 6, cholesterol: 0, satFat: 0.32, description: "Beans, great northern, mature seeds, raw" },
  "black eyed peas": { kcal: 116, protein: 7.7, fat: 0.5, carbs: 20.3, fiber: 5.5, sugars: 3.3, sodium: 4, cholesterol: 0, satFat: 0, description: "Cowpeas, common (blackeyes), mature seeds, cooked" },
  // voda (USDA je nalazio "water convolvulus" = vodeni spinat)
  "cold water": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 0, description: "Water, tap" },
  "warm water": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 0, description: "Water, tap" },
  "boiling water": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 0, description: "Water, tap" },
  "soda water": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 0, description: "Water, carbonated" },
  // rose water (USDA nalazio "Wine, rose")
  "rose water": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 0, description: "Water, rose flower" },
  // baking powder — carbs 27.6 je bilo pogresno (pravi je ~0)
  "baking powder": { kcal: 53, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 10608, cholesterol: 0, satFat: 0, description: "Leavening agents, baking powder, double-acting" },
  // === masovna korekcija pogresnih USDA food izbora (classes D/A/B) ===
  "water chestnut": { kcal: 74, protein: 1.4, fat: 0.1, carbs: 18, fiber: 3, sugars: 3, sodium: 14, cholesterol: 0, satFat: 0, description: "Water chestnuts, chinese, (matal), raw" },
  "petit pois": { kcal: 81, protein: 5.4, fat: 0.4, carbs: 14, fiber: 5.7, sugars: 5.7, sodium: 5, cholesterol: 0, satFat: 0.1, description: "Peas, green, raw" },
  "unsweetened coconut milk": { kcal: 227, protein: 2.3, fat: 23.8, carbs: 5.5, fiber: 2.2, sugars: 3.3, sodium: 15, cholesterol: 0, satFat: 21, description: "Coconut milk, unsweetened" },
  "cooked beetroot": { kcal: 44, protein: 1.7, fat: 0.2, carbs: 10, fiber: 2, sugars: 6.8, sodium: 78, cholesterol: 0, satFat: 0, description: "Beets, cooked, boiled, drained" },
  "lamb stock": { kcal: 7, protein: 0.6, fat: 0.2, carbs: 0.6, fiber: 0, sugars: 0.3, sodium: 700, cholesterol: 0, satFat: 0, description: "Lamb broth" },
  "chilli powder": { kcal: 282, protein: 13.5, fat: 14.3, carbs: 49.7, fiber: 34.8, sugars: 7.2, sodium: 168, cholesterol: 0, satFat: 2.2, description: "Spices, chili powder" },
  "hot chilli powder": { kcal: 282, protein: 13.5, fat: 14.3, carbs: 49.7, fiber: 34.8, sugars: 7.2, sodium: 168, cholesterol: 0, satFat: 2.2, description: "Spices, chili powder" },
  "red chilli powder": { kcal: 282, protein: 13.5, fat: 14.3, carbs: 49.7, fiber: 34.8, sugars: 7.2, sodium: 168, cholesterol: 0, satFat: 2.2, description: "Spices, chili powder" },
  "red chilli flakes": { kcal: 318, protein: 12, fat: 17, carbs: 56, fiber: 27, sugars: 10, sodium: 100, cholesterol: 0, satFat: 3.3, description: "Peppers, hot chili, red, dried, crushed" },
  "chilli flakes": { kcal: 318, protein: 12, fat: 17, carbs: 56, fiber: 27, sugars: 10, sodium: 100, cholesterol: 0, satFat: 3.3, description: "Peppers, hot chili, red, dried, crushed" },
  "red pepper flakes": { kcal: 318, protein: 12, fat: 17, carbs: 56, fiber: 27, sugars: 10, sodium: 100, cholesterol: 0, satFat: 3.3, description: "Peppers, hot chili, red, dried, crushed" },
  "dried red chillies": { kcal: 318, protein: 12, fat: 17, carbs: 56, fiber: 27, sugars: 10, sodium: 100, cholesterol: 0, satFat: 3.3, description: "Peppers, hot chili, red, dried" },
  "dried chillies": { kcal: 318, protein: 12, fat: 17, carbs: 56, fiber: 27, sugars: 10, sodium: 100, cholesterol: 0, satFat: 3.3, description: "Peppers, hot chili, red, dried" },
  "wholegrain mustard": { kcal: 66, protein: 4, fat: 3.3, carbs: 5.8, fiber: 0.3, sugars: 0.9, sodium: 480, cholesterol: 0, satFat: 0.2, description: "Mustard, prepared, with horseradish" },
  "golden syrup": { kcal: 310, protein: 0, fat: 0, carbs: 77, fiber: 0, sugars: 77, sodium: 90, cholesterol: 0, satFat: 0, description: "Syrup, golden" },
  "pomegranate molasses": { kcal: 177, protein: 0.4, fat: 0.1, carbs: 44, fiber: 0.3, sugars: 38, sodium: 20, cholesterol: 0, satFat: 0, description: "Pomegranate molasses" },
  "glace cherry": { kcal: 165, protein: 0.5, fat: 0.2, carbs: 42, fiber: 1.5, sugars: 40, sodium: 15, cholesterol: 0, satFat: 0, description: "Candied cherry (glace)" },
  "vanilla pod": { kcal: 288, protein: 1.9, fat: 0, carbs: 13, fiber: 0, sugars: 13, sodium: 9, cholesterol: 0, satFat: 0, description: "Vanilla extract, imitation, alcohol" },
  "almond extract": { kcal: 313, protein: 0, fat: 0, carbs: 42, fiber: 0, sugars: 42, sodium: 14, cholesterol: 0, satFat: 0, description: "Vanilla extract imitation" },
  "almond essence": { kcal: 313, protein: 0, fat: 0, carbs: 42, fiber: 0, sugars: 42, sodium: 14, cholesterol: 0, satFat: 0, description: "Vanilla extract imitation" },
  "vanilla powder": { kcal: 247, protein: 4, fat: 1, carbs: 80, fiber: 20, sugars: 2, sodium: 10, cholesterol: 0, satFat: 0, description: "Vanilla beans, dried, ground" },
  "sweet sherry": { kcal: 137, protein: 0.2, fat: 0, carbs: 6, fiber: 0, sugars: 6, sodium: 4, cholesterol: 0, satFat: 0, description: "Sherry, dry" },
  "sweet quark": { kcal: 69, protein: 12, fat: 0.3, carbs: 4, fiber: 0, sugars: 4, sodium: 40, cholesterol: 3, satFat: 0.2, description: "Quark, lowfat" },
  "dry white wine": { kcal: 82, protein: 0.1, fat: 0, carbs: 2.6, fiber: 0, sugars: 0.8, sodium: 5, cholesterol: 0, satFat: 0, description: "Alcoholic beverage, wine, white, dry" },
  "dry sherry": { kcal: 137, protein: 0.2, fat: 0, carbs: 6, fiber: 0, sugars: 6, sodium: 4, cholesterol: 0, satFat: 0, description: "Sherry, dry" },
  "shaoxing wine": { kcal: 82, protein: 0.1, fat: 0, carbs: 2.6, fiber: 0, sugars: 0.8, sodium: 5, cholesterol: 0, satFat: 0, description: "Wine, chinese rice wine" },
  "red wine jelly": { kcal: 85, protein: 0.1, fat: 0, carbs: 3, fiber: 0, sugars: 3, sodium: 5, cholesterol: 0, satFat: 0, description: "Red wine" },
  "small potatoes": { kcal: 74, protein: 1.81, fat: 0.26, carbs: 16, fiber: 13.8, sugars: 0, sodium: 2, cholesterol: 0, satFat: 0, description: "Potatoes, raw" },
  "jersey royal potatoes": { kcal: 74, protein: 1.81, fat: 0.26, carbs: 16, fiber: 13.8, sugars: 0, sodium: 2, cholesterol: 0, satFat: 0, description: "Potatoes, raw" },
  "baby new potatoes": { kcal: 74, protein: 1.81, fat: 0.26, carbs: 16, fiber: 13.8, sugars: 0, sodium: 2, cholesterol: 0, satFat: 0, description: "Potatoes, raw" },
  "new potatoes": { kcal: 87, protein: 1.87, fat: 0.1, carbs: 20.1, fiber: 2, sugars: 0.8, sodium: 6, cholesterol: 0, satFat: 0.03, description: "Potatoes, new, raw" },
  "floury potatoes": { kcal: 83, protein: 2.27, fat: 0.36, carbs: 17.8, fiber: 14.9, sugars: 0, sodium: 3, cholesterol: 0, satFat: 0, description: "Potatoes, russet, raw" },
  "charlotte potatoes": { kcal: 74, protein: 1.81, fat: 0.26, carbs: 16, fiber: 13.8, sugars: 0, sodium: 2, cholesterol: 0, satFat: 0, description: "Potatoes, raw" },
  "beef fillet": { kcal: 143, protein: 21.1, fat: 6.46, carbs: 0.18, fiber: 0, sugars: 0, sodium: 45, cholesterol: 64, satFat: 2.4, description: "Beef, tenderloin, separable lean only, raw" },
  "fillet of steak": { kcal: 143, protein: 21.1, fat: 6.46, carbs: 0.18, fiber: 0, sugars: 0, sodium: 45, cholesterol: 64, satFat: 2.4, description: "Beef, tenderloin, separable lean only, raw" },
  "skirty steak": { kcal: 164, protein: 20.1, fat: 9.4, carbs: 0, fiber: 0, sugars: 0, sodium: 51, cholesterol: 64, satFat: 3.9, description: "Beef, flank, steak, boneless, choice, raw" },
  "raw king prawns": { kcal: 71, protein: 15.6, fat: 0.8, carbs: 0.48, fiber: 0, sugars: 0, sodium: 475, cholesterol: 161, satFat: 0.25, description: "Crustaceans, shrimp, raw" },
  "raw tiger prawns": { kcal: 71, protein: 15.6, fat: 0.8, carbs: 0.48, fiber: 0, sugars: 0, sodium: 475, cholesterol: 161, satFat: 0.25, description: "Crustaceans, shrimp, raw" },
  "king prawns": { kcal: 71, protein: 15.6, fat: 0.8, carbs: 0.48, fiber: 0, sugars: 0, sodium: 475, cholesterol: 161, satFat: 0.25, description: "Crustaceans, shrimp, raw" },
  "raw frozen prawns": { kcal: 71, protein: 15.6, fat: 0.8, carbs: 0.48, fiber: 0, sugars: 0, sodium: 475, cholesterol: 161, satFat: 0.25, description: "Crustaceans, shrimp, raw" },
  "baby aubergine": { kcal: 26, protein: 0.85, fat: 0.12, carbs: 5.4, fiber: 2.45, sugars: 2.1, sodium: 0, cholesterol: 0, satFat: 0, description: "Eggplant, raw" },
  "pork knuckle": { kcal: 171, protein: 19.1, fat: 10.5, carbs: 0, fiber: 0, sugars: 0, sodium: 60, cholesterol: 75, satFat: 3.7, description: "Pork, hock, fresh, raw" },
  "soya bean": { kcal: 147, protein: 13, fat: 6.8, carbs: 11, fiber: 4.2, sugars: 3, sodium: 15, cholesterol: 0, satFat: 0.79, description: "Soybeans, green, raw" },
  "sushi rice": { kcal: 359, protein: 7.04, fat: 1.03, carbs: 80.3, fiber: 2.77, sugars: 0.8, sodium: 0, cholesterol: 0, satFat: 0.28, description: "Rice, white, long grain, raw" },
  "chestnut mushroom": { kcal: 30, protein: 3.09, fat: 0.2, carbs: 4.01, fiber: 1.78, sugars: 4, sodium: 5, cholesterol: 0, satFat: 0, description: "Mushrooms, brown, italian or crimini, raw" },
  "porridge oats": { kcal: 382, protein: 13.5, fat: 5.89, carbs: 68.7, fiber: 10.4, sugars: 1, sodium: 1, cholesterol: 0, satFat: 1.03, description: "Oats, rolled" },
  "rolled oats": { kcal: 382, protein: 13.5, fat: 5.89, carbs: 68.7, fiber: 10.4, sugars: 1, sodium: 1, cholesterol: 0, satFat: 1.03, description: "Oats, rolled" },
  "ground oats": { kcal: 389, protein: 13.2, fat: 6.31, carbs: 69.9, fiber: 12.9, sugars: 0.9, sodium: 4, cholesterol: 0, satFat: 1.11, description: "Oats flour" },
  "sour milk": { kcal: 43, protein: 3.46, fat: 1.08, carbs: 4.81, fiber: 0, sugars: 4.8, sodium: 93, cholesterol: 5, satFat: 0.65, description: "Buttermilk, lowfat" },
  "black pudding": { kcal: 379, protein: 14.6, fat: 34.5, carbs: 1.29, fiber: 0, sugars: 0, sodium: 680, cholesterol: 150, satFat: 13.4, description: "Sausage, blood" },
  "dark chocolate chips": { kcal: 480, protein: 4.2, fat: 30, carbs: 63.9, fiber: 5.9, sugars: 47.4, sodium: 11, cholesterol: 0, satFat: 17.75, description: "Chocolate, dark, chips" },
  "beef stock cubes": { kcal: 437, protein: 16.7, fat: 13.9, carbs: 64.9, fiber: 0.2, sugars: 0, sodium: 1070, cholesterol: 0, satFat: 3.43, description: "Soup, bouillon cubes and granules, dry" },
  "tobasco sauce": { kcal: 12, protein: 1.29, fat: 0.76, carbs: 0.8, fiber: 0.6, sugars: 0, sodium: 633, cholesterol: 0, satFat: 0.11, description: "Sauce, hot pepper, tabasco" },
  "pigs trotters": { kcal: 171, protein: 19.1, fat: 10.5, carbs: 0, fiber: 0, sugars: 0, sodium: 60, cholesterol: 75, satFat: 3.7, description: "Pork, hock, fresh, raw" },
  "cocoy banana": { kcal: 85, protein: 0.73, fat: 0.22, carbs: 20.1, fiber: 1.7, sugars: 12.2, sodium: 0, cholesterol: 0, satFat: 0, description: "Bananas, raw" },
  "raw yucca": { kcal: 159, protein: 1.36, fat: 0.28, carbs: 38.1, fiber: 1.8, sugars: 1.7, sodium: 14, cholesterol: 0, satFat: 0.07, description: "Cassava, raw" },
  "daikon radish": { kcal: 20, protein: 0.66, fat: 0.08, carbs: 4.06, fiber: 1.31, sugars: 1.9, sodium: 51, cholesterol: 0, satFat: 0, description: "Radishes, raw" },
  "pitted dates": { kcal: 277, protein: 1.81, fat: 0.15, carbs: 75, fiber: 6.7, sugars: 66.5, sodium: 1, cholesterol: 0, satFat: 0.03, description: "Dates, medjool" },
  "mustard powder": { kcal: 509, protein: 26.1, fat: 36.2, carbs: 28.1, fiber: 12.2, sugars: 6.6, sodium: 13, cholesterol: 0, satFat: 1.99, description: "Mustard, seed, ground" },
  "vegetable stock cube": { kcal: 437, protein: 16.7, fat: 13.9, carbs: 64.9, fiber: 0.2, sugars: 0, sodium: 1070, cholesterol: 0, satFat: 3.43, description: "Soup, bouillon cubes and granules, dry" },
  "garlic bulb": { kcal: 143, protein: 6.62, fat: 0.38, carbs: 28.2, fiber: 2.7, sugars: 0.9, sodium: 0, cholesterol: 0, satFat: 0, description: "Garlic, raw" },
  "ginger paste": { kcal: 80, protein: 1.82, fat: 0.75, carbs: 17.8, fiber: 2, sugars: 1.7, sodium: 13, cholesterol: 0, satFat: 0.2, description: "Ginger root, raw" },
  "soured cream and chive dip": { kcal: 196, protein: 3.07, fat: 18, carbs: 5.56, fiber: 0, sugars: 1.2, sodium: 50, cholesterol: 0, satFat: 10.7, description: "Sour cream, cultured" },
  "wonton skin": { kcal: 292, protein: 9.8, fat: 1.5, carbs: 57.9, fiber: 1.8, sugars: 0.3, sodium: 572, cholesterol: 0, satFat: 0.26, description: "Wonton wrappers" },
  "chicken stock cube": { kcal: 437, protein: 16.7, fat: 13.9, carbs: 64.9, fiber: 0.2, sugars: 0, sodium: 1070, cholesterol: 0, satFat: 3.43, description: "Soup, bouillon cubes and granules, dry" },
  // === visoko-uticajni top100 koji su i dalje bili pogresni (classes D/A) ===
  "greek yogurt": { kcal: 97, protein: 9, fat: 0.4, carbs: 3.6, fiber: 0, sugars: 3.2, sodium: 41, cholesterol: 5, satFat: 0.1, description: "Yogurt, Greek, plain, nonfat" },
  mushrooms: { kcal: 22, protein: 3.1, fat: 0.3, carbs: 3.3, fiber: 1, sugars: 1.6, sodium: 5, cholesterol: 0, satFat: 0.1, description: "Mushrooms, white, raw" },
  courgettes: { kcal: 17, protein: 1.2, fat: 0.3, carbs: 3.1, fiber: 1, sugars: 2.5, sodium: 8, cholesterol: 0, satFat: 0.1, description: "Squash, zucchini, raw" },
  sweetcorn: { kcal: 86, protein: 3.3, fat: 1.4, carbs: 19, fiber: 2, sugars: 3.2, sodium: 15, cholesterol: 0, satFat: 0.2, description: "Corn, sweet, yellow, raw" },
  "sweet potatoes": { kcal: 86, protein: 1.6, fat: 0.1, carbs: 20.1, fiber: 3, sugars: 4.2, sodium: 55, cholesterol: 0, satFat: 0, description: "Sweet potato, raw" },
  "butter beans": { kcal: 115, protein: 8, fat: 0.4, carbs: 20, fiber: 5, sugars: 1.9, sodium: 250, cholesterol: 0, satFat: 0.1, description: "Lima beans, large, mature seeds, cooked, boiled" },
  almonds: { kcal: 579, protein: 21.2, fat: 49.9, carbs: 21.6, fiber: 12.5, sugars: 4.4, sodium: 1, cholesterol: 0, satFat: 3.8, description: "Nuts, almonds, raw" },
  plantain: { kcal: 122, protein: 1.3, fat: 0.4, carbs: 31.9, fiber: 2.3, sugars: 15, sodium: 4, cholesterol: 0, satFat: 0.1, description: "Plantains, raw" },
  rice: { kcal: 359, protein: 7, fat: 1, carbs: 79, fiber: 1.7, sugars: 0, sodium: 1, cholesterol: 0, satFat: 0.2, description: "Rice, white, long grain, raw" },
  clams: { kcal: 86, protein: 14.7, fat: 1, carbs: 3.6, fiber: 0, sugars: 0, sodium: 56, cholesterol: 34, satFat: 0.1, description: "Mollusks, clam, mixed species, raw" },
  "green beans": { kcal: 31, protein: 1.8, fat: 0.2, carbs: 7, fiber: 2.7, sugars: 3.3, sodium: 6, cholesterol: 0, satFat: 0, description: "Beans, snap, green, raw" },
  "cinnamon stick": { kcal: 247, protein: 4, fat: 1.2, carbs: 80, fiber: 53, sugars: 2.2, sodium: 10, cholesterol: 0, satFat: 0.3, description: "Spices, cinnamon, ground" },
  // === klasa D — opis je bila SASVIM druga hrana (ispravljen kompletni makro set) ===
  "white fish fillets": { kcal: 90, protein: 19, fat: 1, carbs: 0, fiber: 0, sugars: 0, sodium: 60, cholesterol: 50, satFat: 0.2, description: "Fish, white, generic, raw (cod/haddock type)" },
  "frozen seafood mix": { kcal: 93, protein: 15, fat: 1.5, carbs: 3, fiber: 0, sugars: 0, sodium: 100, cholesterol: 60, satFat: 0.4, description: "Seafood mixed (shrimp, mussels, squid, calamari), raw" },
  "vegetable millk": { kcal: 33, protein: 2.8, fat: 1.8, carbs: 1.5, fiber: 0.3, sugars: 0.9, sodium: 40, cholesterol: 0, satFat: 0.2, description: "Soy milk, fortified" },
  "kabanos sausages": { kcal: 280, protein: 18, fat: 22, carbs: 1.5, fiber: 0, sugars: 0.5, sodium: 1200, cholesterol: 70, satFat: 8, description: "Kabanos (dry fermented sausage), pork" },
  "christmas pudding": { kcal: 250, protein: 3.5, fat: 7, carbs: 45, fiber: 2.5, sugars: 32, sodium: 60, cholesterol: 30, satFat: 3, description: "Pudding, Christmas, grain, dried fruit" },
  "doner meat": { kcal: 210, protein: 22, fat: 14, carbs: 1, fiber: 0, sugars: 0, sodium: 500, cholesterol: 60, satFat: 5, description: "Gyro/doner meat, lamb and beef, cooked" },
  "sour pork sausage": { kcal: 340, protein: 15, fat: 30, carbs: 2, fiber: 0, sugars: 1, sodium: 700, cholesterol: 75, satFat: 11, description: "Sausage, pork, smoked/fermented, sour" },
  "strained yoghurt": { kcal: 97, protein: 9, fat: 0.4, carbs: 3.6, fiber: 0, sugars: 3.2, sodium: 41, cholesterol: 5, satFat: 0.1, description: "Yogurt, Greek, plain, nonfat" },
  "soya milk": { kcal: 33, protein: 2.8, fat: 1.8, carbs: 1.5, fiber: 0.3, sugars: 0.9, sodium: 40, cholesterol: 0, satFat: 0.2, description: "Soy milk, fortified" },
  "candied peel": { kcal: 315, protein: 0.5, fat: 0.1, carbs: 80, fiber: 1, sugars: 70, sodium: 120, cholesterol: 0, satFat: 0, description: "Citrus peel, candied" },
  "mixed peel": { kcal: 315, protein: 0.5, fat: 0.1, carbs: 80, fiber: 1, sugars: 70, sodium: 120, cholesterol: 0, satFat: 0, description: "Citrus peel, candied" },
  "alinos sauce": { kcal: 250, protein: 2, fat: 22, carbs: 12, fiber: 1, sugars: 6, sodium: 900, cholesterol: 40, satFat: 6, description: "Sauce, cream-based (mayonnaise/sour cream type)" },
  "toor dal": { kcal: 320, protein: 22, fat: 1.5, carbs: 60, fiber: 10, sugars: 3, sodium: 10, cholesterol: 0, satFat: 0.2, description: "Pigeon peas (toor dal/toovar), mature seeds, raw" },
  "flat rice noodles": { kcal: 109, protein: 2, fat: 0.2, carbs: 24, fiber: 1, sugars: 0, sodium: 50, cholesterol: 0, satFat: 0.05, description: "Rice noodles, cooked" },
  "peanut cookies": { kcal: 500, protein: 9, fat: 27, carbs: 58, fiber: 3, sugars: 25, sodium: 350, cholesterol: 20, satFat: 6, description: "Cookies, peanut" },
  "ground poppy seeds": { kcal: 525, protein: 18, fat: 42, carbs: 28, fiber: 20, sugars: 3, sodium: 26, cholesterol: 0, satFat: 4.5, description: "Spices, poppy seed" },
  "polish kabanos": { kcal: 280, protein: 18, fat: 22, carbs: 1.5, fiber: 0, sugars: 0.5, sodium: 1200, cholesterol: 70, satFat: 8, description: "Kabanos (dry fermented sausage), pork" },
  "light raisins": { kcal: 299, protein: 3.1, fat: 0.5, carbs: 79, fiber: 3.7, sugars: 59, sodium: 11, cholesterol: 0, satFat: 0.1, description: "Raisins, golden seedless" },
  "chinese sesame sauce": { kcal: 595, protein: 17, fat: 54, carbs: 17, fiber: 6, sugars: 3, sodium: 100, cholesterol: 0, satFat: 8, description: "Sesame butter (tahini)" },
  "mature cheddar": { kcal: 403, protein: 25, fat: 33, carbs: 1.3, fiber: 0, sugars: 0.5, sodium: 621, cholesterol: 105, satFat: 21, description: "Cheese, cheddar, mature" },
  "thai chilli jam": { kcal: 170, protein: 1, fat: 0.5, carbs: 40, fiber: 2, sugars: 35, sodium: 600, cholesterol: 0, satFat: 0.1, description: "Chili jam (nam prik pao-style)" },
  "whole black peppercorns": { kcal: 251, protein: 10, fat: 3.3, carbs: 64, fiber: 26, sugars: 0.6, sodium: 20, cholesterol: 0, satFat: 1.4, description: "Spices, pepper, black" },
  "ground mahleb": { kcal: 578, protein: 13, fat: 48, carbs: 40, fiber: 18, sugars: 7, sodium: 25, cholesterol: 0, satFat: 5, description: "Spices, mahleb (ground sour cherry pits)" },
  "speculaas spice mix": { kcal: 340, protein: 7, fat: 12, carbs: 65, fiber: 20, sugars: 5, sodium: 50, cholesterol: 0, satFat: 2, description: "Spices, speculaas/gingerbread blend (cinnamon, cloves, nutmeg)" },
  "biryani masala": { kcal: 310, protein: 11, fat: 12, carbs: 50, fiber: 25, sugars: 5, sodium: 150, cholesterol: 0, satFat: 2, description: "Spices, biryani masala blend" },
  "caramelized sugar sauce": { kcal: 300, protein: 0.5, fat: 0.3, carbs: 75, fiber: 0, sugars: 70, sodium: 60, cholesterol: 0, satFat: 0, description: "Caramel sauce (caramelized sugar)" },
  "pink food colouring": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 0, description: "Food coloring, pink (water-based)" },
  "gingerbread spice": { kcal: 340, protein: 7, fat: 12, carbs: 65, fiber: 20, sugars: 5, sodium: 50, cholesterol: 0, satFat: 2, description: "Spices, gingerbread blend" },
  "kabse spice": { kcal: 310, protein: 11, fat: 12, carbs: 50, fiber: 25, sugars: 5, sodium: 130, cholesterol: 0, satFat: 2, description: "Spices, kabse (Arabian five-spice blend)" },
  "italian seasoning": { kcal: 250, protein: 10, fat: 6, carbs: 50, fiber: 30, sugars: 4, sodium: 40, cholesterol: 0, satFat: 1, description: "Spices, italian seasoning blend" },
  "ice cubes": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 0, description: "Water, frozen (ice)" },
  "fruit mix": { kcal: 60, protein: 0.8, fat: 0.2, carbs: 15, fiber: 2, sugars: 12, sodium: 5, cholesterol: 0, satFat: 0, description: "Mixed fruit (dried)", },
  "yellow food colouring": { kcal: 0, protein: 0, fat: 0, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 0, description: "Food coloring, yellow (water-based)" },
  "truffle oil": { kcal: 884, protein: 0, fat: 100, carbs: 0, fiber: 0, sugars: 0, sodium: 0, cholesterol: 0, satFat: 15, description: "Oil, truffle-flavored (vegetable oil base)" },
  "oreo cream biscuits": { kcal: 473, protein: 5, fat: 20, carbs: 70, fiber: 3, sugars: 40, sodium: 440, cholesterol: 0, satFat: 7, description: "Cookies, chocolate sandwich cream (Oreo-type)" },
  "toffee popcorn": { kcal: 425, protein: 5, fat: 15, carbs: 72, fiber: 4, sugars: 45, sodium: 400, cholesterol: 0, satFat: 3, description: "Candy/caramel corn (toffee popcorn)" },
  "smoky aïoli": { kcal: 330, protein: 1, fat: 35, carbs: 4, fiber: 0, sugars: 2, sodium: 400, cholesterol: 30, satFat: 5, description: "Mayonnaise aioli, smokey" },
  "chinese leaf": { kcal: 13, protein: 1.5, fat: 0.2, carbs: 2.2, fiber: 1, sugars: 1.2, sodium: 65, cholesterol: 0, satFat: 0, description: "Cabbage, Chinese (pak-choi/naapa), raw" },
  "baby pak koi": { kcal: 13, protein: 1.5, fat: 0.2, carbs: 2.2, fiber: 1, sugars: 1.2, sodium: 65, cholesterol: 0, satFat: 0, description: "Cabbage, pak choi (bok choy), baby, raw" },
  // === sastojci koji su nedostajali u bazi (vezali smo ih na postojece/pravne vrednosti) ===
  "chives": { kcal: 30, protein: 3.27, fat: 0.73, carbs: 4.35, fiber: 2.5, sugars: 1.9, sodium: 3, cholesterol: 0, satFat: 0.15, description: "Chives, raw" },
  "cloves": { kcal: 274, protein: 5.97, fat: 13, carbs: 65.5, fiber: 34, sugars: 2.4, sodium: 243, cholesterol: 0, satFat: 4.4, description: "Spices, cloves, ground" },
  "lemongrass": { kcal: 99, protein: 1.82, fat: 0.49, carbs: 25.3, fiber: 1.2, sugars: 1.2, sodium: 6, cholesterol: 0, satFat: 0.12, description: "Lemongrass (citronella), raw" },
  "lemongrass stalks": { kcal: 99, protein: 1.82, fat: 0.49, carbs: 25.3, fiber: 1.2, sugars: 1.2, sodium: 6, cholesterol: 0, satFat: 0.12, description: "Lemongrass (citronella), raw" },
  // egzotični bez USDA reference — procenjeni na osnovu sastava
  "khus khus": { kcal: 525, protein: 18, fat: 42, carbs: 28, fiber: 19, sugars: 3, sodium: 10, cholesterol: 0, satFat: 5, description: "Poppy seeds (khus khus)" },
  "knafeh": { kcal: 340, protein: 7, fat: 16, carbs: 45, fiber: 1, sugars: 25, sodium: 250, cholesterol: 45, satFat: 8, description: "Knafeh (kataifi pastry, cheese, syrup)" },
  "mulukhiyah": { kcal: 37, protein: 4.7, fat: 0.7, carbs: 5.8, fiber: 3, sugars: 2, sodium: 80, cholesterol: 0, satFat: 0.1, description: "Molokhia (Corchorus olitorius), cooked" },
  "nougatine": { kcal: 480, protein: 6, fat: 22, carbs: 65, fiber: 2, sugars: 50, sodium: 40, cholesterol: 0, satFat: 10, description: "Nougatine (caramelized sugar with nuts)" },
  "prahok": { kcal: 120, protein: 20, fat: 3, carbs: 5, fiber: 0, sugars: 0, sodium: 6000, cholesterol: 80, satFat: 1, description: "Prahok (fermented fish paste)" },
  "sevaiiya": { kcal: 365, protein: 12, fat: 1.5, carbs: 75, fiber: 3, sugars: 2, sodium: 10, cholesterol: 0, satFat: 0.3, description: "Vermicelli rice noodles (sevaiiya)" },
};

let fixed = 0;
for (const [k, v] of Object.entries(FIXES)) {
  const existing = cache[k];
  if (!existing) continue;
  const { description, ...per100 } = v;
  cache[k] = {
    ...existing,
    description: description || existing.description || "manual",
    per100,
  };
  fixed++;
}
fs.writeFileSync(CACHE_PATH, JSON.stringify(cache, null, 1));
console.log(`[OK] Popravljeno ${fixed} sastojaka u kešu`);
